version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    env_file:
      - .env.docker
    ports:
      - "8080:8080" # ✅ Railway espera el puerto 8080

  queue_worker:
    build: .
    container_name: laravel_queue
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work
    depends_on:
      - app
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
