version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    env_file:
      - .env.docker
    ports:
      - "8080:8080" # ✅ Railway espera el puerto 8080

networks:
  laravel:
